### ISSUE TITLE
Multi-Arch Support in v0.45.0

### ISSUE THREAD

**Issue by patrickbussmann** [ome/ansible-role-cadvisor#9]
Thanks for this ansible script.
But its not working since v0.45.0 so I have to stick to v0.44.0

```
- role: ome.cadvisor
  vars:
    cadvisor_version: v0.44.0
    cadvisor_checksum: c7de202fe8886762c65dd03c567c19d82d71a0a46739ef0bc760a980d1116f6b
```

Problem is that they introduced some different architectures. So download link is now:
https://github.com/google/cadvisor/releases/download/v0.47.0/cadvisor-v0.47.0-linux-amd64

If I have the time I will also adjust this but for now I stick to v0.44.0 😇
